sonar.projectKey=agentic-taf
sonar.projectName=Agentic-TAF
sonar.projectVersion=1.0.0

sonar.sources=src/main/python
sonar.tests=src/test/python
sonar.sourceEncoding=UTF-8
sonar.language=py

sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.xunit.reportPath=reports/unit-tests.xml

sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/build/**,**/dist/**
